spring.application.name=ms-pedidos

# Configurações do PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/ms-pedidos-db 
spring.datasource.username=postgre
spring.datasource.password=Spalla2026x@ 
spring.jpa.hibernate.ddl-auto=update 

# Exibir SQL gerado no console
spring.jpa.show-sql=true  